Add ENERGY CONNECTOR techMob card
Slimefun-Addon-Community/Supreme pull request #34
Opened 2023-03-31 17:04 UTC by davidcanas

2023-03-31 17:12 UTC, Sefiraat commented
Given most other cards are for the production of raw/base materials, is it appropriate to have one for a fully finished, crafted, item like this?

2023-04-05 12:19 UTC, RelativoBR commented
@davidcanas  Rejected because ready-made components are not the idea, just base features. If you separate only the suggestion of the apple, it will be welcome.

2023-04-05 12:25 UTC, RelativoBR requested changes
to remove CARD_ENERGY_CONNECTOR

2023-04-05 14:45 UTC, davidcanas commented
done

2023-04-05 14:53 UTC, Sefiraat requested changes

2023-04-05 14:53 UTC, Sefiraat commented on src/main/java/com/github/relativobr/supreme/setup/SetupSimpleCard.java
> +
```suggestion
```

2023-04-05 15:02 UTC, Sefiraat commented on src/main/java/com/github/relativobr/supreme/resource/mobtech/SimpleCard.java
> +      LoreBuilder.machine(MachineTier.MEDIUM, MachineType.MACHINE), "", "&3Supreme Component");
```suggestion
      LoreBuilder.machine(MachineTier.MEDIUM, MachineType.MACHINE), "", "&3Supreme Component");
```

2023-04-05 15:03 UTC, Sefiraat approved these changes
👍

2023-04-05 15:04 UTC, Sefiraat requested changes

2023-04-05 15:04 UTC, Sefiraat commented on src/main/java/com/github/relativobr/supreme/resource/mobtech/SimpleCard.java
> +      "&bCard Machine Snow", "", "&fChange to Production Apple", "",
Whoops, saw this too late! 
```suggestion
      "&bCard Machine Apple", "", "&fChange to Production Apple", "",
```

2023-04-05 17:02 UTC, davidcanas commented on src/main/java/com/github/relativobr/supreme/resource/mobtech/SimpleCard.java
> +      "&bCard Machine Snow", "", "&fChange to Production Apple", "",
wtf

2023-04-05 17:12 UTC, Sefiraat approved these changes
👍

2023-04-06 18:45 UTC, RelativoBR approved these changes

2023-04-06 18:47 UTC, merged