issues-36: Option to limit the use of machine
Slimefun-Addon-Community/Supreme pull request #37
Opened 2023-04-06 21:56 UTC by RelativoBR

Correction of some misspelled words and inclusion of a quantity limiter of 4 MobTech machines per chuck, during the onPlace event, checking the type of material in the chunk.

2023-04-06 22:09 UTC, JustAHuman-xD requested changes
Not sure that's how I would implement it, I'd look for a more performant and cleaner way.

2023-04-06 22:09 UTC, JustAHuman-xD commented on src/main/java/com/github/relativobr/supreme/util/UtilMachine.java
> +  }
I would not do this like this it's laggy and just not a great way to do it, instead I would save a counter in the chunks storage and check that instead, this also would count non -slimefun blocks and just is not something you want to do. By getting the storage in the on place and adding to it, and the opposite when removing. Just an idea though there are definitely other ways.

2023-04-06 22:09 UTC, JustAHuman-xD commented on src/main/java/com/github/relativobr/supreme/machine/tech/TechRobotic.java
> +        }
I would do something to help the readability of this

2023-04-06 22:09 UTC, JustAHuman-xD commented on src/main/java/com/github/relativobr/supreme/machine/tech/TechMutation.java
> +                  Supreme.getSupremeOptions().getChunkLimitMaxTechMutation() + "x Material)");
Readability and potentially abstract this?

2023-04-06 22:09 UTC, JustAHuman-xD commented on src/main/java/com/github/relativobr/supreme/machine/tech/TechGenerator.java
> +        }
Readability and potentially abstraction

2023-04-06 22:09 UTC, JustAHuman-xD commented on src/main/java/com/github/relativobr/supreme/machine/tech/MobTechCollector.java
> +        }
Readability and potential abstraction

2023-04-06 22:17 UTC, RelativoBR commented on src/main/java/com/github/relativobr/supreme/util/UtilMachine.java
> +  }
Not sure how to implement your suggestion, could you help with that part? Or do you have any examples of these mechanisms?

2023-04-06 23:26 UTC, JustAHuman-xD commented
And I'll look into a way to make them more performant

2023-04-12 18:08 UTC, RelativoBR commented
new PR: https://github.com/Slimefun-Addon-Community/Supreme/pull/42

2023-04-12 18:08 UTC, closed without merging